FROM nginx:alpine

# Копируем конфигурационные файлы
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx-default.conf /etc/nginx/conf.d/default.conf

# Создаем структуру директорий
RUN mkdir -p /usr/share/nginx/html/static/legacy
RUN mkdir -p /usr/share/nginx/html/static/img

# Копируем статические файлы
COPY static/ /usr/share/nginx/html/static/
COPY docs/ /usr/share/nginx/html/docs/
COPY README.md /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]