FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ./src/ .

RUN dotnet restore
RUN dotnet publish Eventity.DataService/Eventity.DataService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://*:5003
EXPOSE 5003

ENTRYPOINT ["dotnet", "Eventity.DataService.dll"]
