FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ./src/ .

RUN dotnet restore
RUN dotnet publish Eventity.CoreService/Eventity.CoreService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://*:5002
EXPOSE 5002

ENTRYPOINT ["dotnet", "Eventity.CoreService.dll"]
