FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/html/static
COPY ./static /usr/share/nginx/html/static/

RUN mkdir -p /usr/share/nginx/html/static/legacy
RUN mkdir -p /usr/share/nginx/html/static/img
RUN mkdir -p /usr/share/nginx/html/docs

COPY static/ /usr/share/nginx/html/static/
COPY README.md /usr/share/nginx/html/
COPY docs/ /usr/share/nginx/html/docs/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]