global using Xunit;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Eventity.Domain.Exceptions;
global using Eventity.Domain.Interfaces.Repositories;
global using Eventity.Domain.Models;
global using Moq;
