// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Eventity.Tests.E2E.FA.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "2FA")]
    public partial class ДвухфакторнаяАутентификацияFeature : object, Xunit.IClassFixture<ДвухфакторнаяАутентификацияFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "2FA"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ДвухфакторнаяАутентификацияFeature(ДвухфакторнаяАутентификацияFeature.FixtureData fixtureData, Eventity_Tests_E2E_FA_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru"), "features", "Двухфакторная аутентификация", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Успешная аутентификация с 2FA")]
        [Xunit.TraitAttribute("FeatureTitle", "Двухфакторная аутентификация")]
        [Xunit.TraitAttribute("Description", "Успешная аутентификация с 2FA")]
        public void УспешнаяАутентификацияС2FA()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успешная аутентификация с 2FA", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("существует технический пользователь с логином \'techuser\' и паролем \'TestPass123!\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                testRunner.And("включена двухфакторная аутентификация", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
                testRunner.When("пользователь пытается войти с логином \'techuser\' и паролем \'TestPass123!\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
                testRunner.Then("требуется ввести код подтверждения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
                testRunner.And("получен код подтверждения по email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
                testRunner.When("пользователь вводит правильный код подтверждения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
                testRunner.Then("аутентификация успешна и выдан JWT токен", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
                testRunner.And("получен доступ к защищенным ресурсам", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Плановая смена пароля после аутентификации")]
        [Xunit.TraitAttribute("FeatureTitle", "Двухфакторная аутентификация")]
        [Xunit.TraitAttribute("Description", "Плановая смена пароля после аутентификации")]
        [Xunit.TraitAttribute("Category", "PasswordChange")]
        public void ПлановаяСменаПароляПослеАутентификации()
        {
            string[] tagsOfScenario = new string[] {
                    "PasswordChange"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Плановая смена пароля после аутентификации", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("существует технический пользователь с логином \'changepassuser\' и паролем \'OldPass" +
                        "123!\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                testRunner.And("пользователь успешно аутентифицирован с 2FA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
                testRunner.When("пользователь отправляет запрос на смену пароля с текущим паролем \'OldPass123!\' и " +
                        "новым паролем \'NewPass456!\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
                testRunner.Then("смена пароля успешна", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
                testRunner.And("пользователь может войти с новым паролем \'NewPass456!\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ДвухфакторнаяАутентификацияFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ДвухфакторнаяАутентификацияFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
